### ISSUE TITLE
Handle Kafka server connection states

### ISSUE THREAD

**Issue by dccurtis** [project-koku/masu#237]
The Kafka message handler currently operates only when the Kafka server is running at all times.

If the Kafka server remains running the worker can successfully be started, stopped, and restarted.

We need handle the following case:
* Server stops and restarts while the worker remains running. (Need to keep the daemon thread running at all times with some re-try logic on timeout).

Capturing and logging all connection failures should also be done as part of this effort.

Being able to reconfigure the server address without restarting the worker could be considered a stretch goal.

**Comment by dccurtis** [comment]
I ran some tests by restarting the upload service and the masu worker does recover and is able to handle messages properly.  The only problem that remains is that while the upload service is down our worker log is heavily spammed.

**Comment by dccurtis** [comment]
In the CI environment the masu worker was failing to connect to the upload service with the following backtrace:

```
[2018-11-28 18:00:32,742: INFO/MainProcess] Stopping kafka worker thread.  Error: Unable to connect to kafka server.  Closing consumer.
[2018-11-28 18:02:58,022: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 322, in start
    blueprint.start(self)
  File "/opt/app-root/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/opt/app-root/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 598, in start
    c.loop(*c.loop_args())
  File "/opt/app-root/lib/python3.6/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/opt/app-root/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "/opt/app-root/lib/python3.6/site-packages/kombu/transport/base.py", line 236, in on_readable
    reader(loop)
  File "/opt/app-root/lib/python3.6/site-packages/kombu/transport/base.py", line 218, in _read
    drain_events(timeout=0)
  File "/opt/app-root/lib/python3.6/site-packages/amqp/connection.py", line 491, in drain_events
    while not self.blocking_read(timeout):
  File "/opt/app-root/lib/python3.6/site-packages/amqp/connection.py", line 497, in blocking_read
    return self.on_inbound_frame(frame)
  File "/opt/app-root/lib/python3.6/site-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/opt/app-root/lib/python3.6/site-packages/amqp/connection.py", line 501, in on_inbound_method
    method_sig, payload, content,
  File "/opt/app-root/lib/python3.6/site-packages/amqp/abstract_channel.py", line 128, in dispatch_method
    listener(*args)
  File "/opt/app-root/lib/python3.6/site-packages/amqp/connection.py", line 621, in _on_close
    self._x_close_ok()
  File "/opt/app-root/lib/python3.6/site-packages/amqp/connection.py", line 636, in _x_close_ok
    self.send_method(spec.Connection.CloseOk, callback=self._on_close_ok)
  File "/opt/app-root/lib/python3.6/site-packages/amqp/abstract_channel.py", line 50, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/opt/app-root/lib/python3.6/site-packages/amqp/method_framing.py", line 166, in write_frame
    write(view[:offset])
  File "/opt/app-root/lib/python3.6/site-packages/amqp/transport.py", line 275, in write
    self._write(s)
ConnectionResetError: [Errno 104] Connection reset by peer
[2018-11-28 18:02:58,097: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq.hccm-ci.svc:5672//: failed to resolve broker hostname.
Trying again in 2.00 seconds...
```

Need to investigate this further add some retry logic in the Kafka handler thread to make an attempt to reconnect

**Comment by blentz** [comment]
@dccurtis  - Ideally, the Kafka handler retry logic should probably be an exponential back-off.

**Comment by adberglund** [comment]
@dccurtis Should we close this with the work done for the listener?
