### ISSUE TITLE
Traceback error showing in logs when trying to calculate charges from rates

### ISSUE THREAD

**Issue by lcouzens** [project-koku/masu#331]
**Describe the bug**
Errors showing in the logs when trying to calculate OCP charges

**To Reproduce**
1. Add OCP provider
2. Add provider rates
3. Wait for initial ingest or force ingest
4. See errors in logs

**Expected behavior**
Charges should be calculated correctly without errors in logs
```
[2019-01-11 14:41:23,726: INFO/ForkPoolWorker-2] Starting charge calculation updates.
[2019-01-11 14:41:23,761: ERROR/ForkPoolWorker-2] Task masu.processor.tasks.update_charge_info[02a0fc11-62ae-4aad-ab5d-24186041b513] raised unexpected: AttributeError("'ReportSchema' object has no attribute 'rates_rate'",)
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/app-root/src/masu/celery/__init__.py", line 75, in __call__
    return self.run(*args, **kwargs)
  File "/opt/app-root/src/masu/processor/tasks.py", line 225, in update_charge_info
    updater.update_charge_info()
  File "/opt/app-root/src/masu/processor/report_charge_updater.py", line 88, in update_charge_info
    self._updater.update_summary_charge_info()
  File "/opt/app-root/src/masu/processor/ocp/ocp_report_charge_updater.py", line 198, in update_summary_charge_info
    self._update_cpu_charge()
  File "/opt/app-root/src/masu/processor/ocp/ocp_report_charge_updater.py", line 145, in _update_cpu_charge
    cpu_usage_rates = rate_accessor.get_cpu_core_usage_per_hour_rates()
  File "/opt/app-root/src/masu/database/ocp_rate_db_accessor.py", line 70, in get_cpu_core_usage_per_hour_rates
    cpu_usage_rates = self.get_rates('cpu_core_usage_per_hour')
  File "/opt/app-root/src/masu/database/ocp_rate_db_accessor.py", line 65, in get_rates
    rate_entry = self._get_base_entry(value)
  File "/opt/app-root/src/masu/database/ocp_rate_db_accessor.py", line 48, in _get_base_entry
    getattr(self.report_schema, table_name),
AttributeError: 'ReportSchema' object has no attribute 'rates_rate'
```
**Context (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Commit: 3011d8e0631a72809f070c36de0e533d89ac0ade

**Additional context**
Initial ingest was collecting first time data from OCP and AWS not sure if this caused any issues, but as a side note the length of time to process the data was longer which is I guess expected. Maybe that had some side affect.

**Comment by blentz** [comment]
I went through the repro steps and was unable to reproduce this bug. It appears to be fixed.

[https://app.zenhub.com/files/132777214/70e74b26-4328-4678-9197-80bacc9f71e5/download](https://app.zenhub.com/files/132777214/70e74b26-4328-4678-9197-80bacc9f71e5/download)
