### ISSUE TITLE
Charge calculation failing on DB lock

### ISSUE THREAD

**Issue by adberglund** [project-koku/masu#380]
**Describe the bug**
OCP charge failed to get calculated when doing data summarization in masu.

```

[2019-02-22 14:28:34,825: ERROR/ForkPoolWorker-1] Task masu.processor.tasks.update_charge_info[c6f97301-8400-45a6-b58b-cb0755047580] raised unexpected: TransactionRollbackError('deadlock detected\nDETAIL:  Process 16556 waits for ShareLock on transaction 164788; blocked by process 16825.\nProcess 16825 waits for ShareLock on transaction 164787; blocked by process 16556.\nHINT:  See server log for query details.\nCONTEXT:  while updating tuple (2,2) in relation "reporting_ocpusagelineitem_daily_summary"\n',)
--
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
  | R = retval = fun(*args, **kwargs)
  | File "/opt/app-root/src/masu/celery/__init__.py", line 75, in __call__
  | return self.run(*args, **kwargs)
  | File "/opt/app-root/src/masu/processor/tasks.py", line 256, in update_charge_info
  | updater.update_charge_info()
  | File "/opt/app-root/src/masu/processor/report_charge_updater.py", line 88, in update_charge_info
  | self._updater.update_summary_charge_info()
  | File "/opt/app-root/src/masu/processor/ocp/ocp_report_charge_updater.py", line 222, in update_summary_charge_info
  | self._update_cpu_charge()
  | File "/opt/app-root/src/masu/processor/ocp/ocp_report_charge_updater.py", line 157, in _update_cpu_charge
  | report_accessor.populate_cpu_charge(total_cpu_charge)
  | File "/opt/app-root/src/masu/database/ocp_report_db_accessor.py", line 315, in populate_cpu_charge
  | self._cursor.execute(charge_line_sql)
  | psycopg2.extensions.TransactionRollbackError: deadlock detected
  | DETAIL:  Process 16556 waits for ShareLock on transaction 164788; blocked by process 16825.
  | Process 16825 waits for ShareLock on transaction 164787; blocked by process 16556.
  | HINT:  See server log for query details.
  | CONTEXT:  while updating tuple (2,2) in relation "reporting_ocpusagelineitem_daily_summary"
```

**To Reproduce**
1. Run the report_data API endpoint to re-summarize data

**Additional context**
I believe doing a bulk update on charge might help instead of a transaction for each updated line.

**Comment by dccurtis** [comment]
Reproduced the problem.
1.  Add 7 OCP providers and rates for all.
2. Generate nise data with the following yaml to ensure the report sizes are large
```
---
generators:
  - OCPGenerator:
      start_date: last_month
      nodes:
        - node:
          node_name: alpha
          cpu_cores: 4
          memory_gig: 16
          resource_id: 55555555
```
3.  Ingest

Logs:
```
worker_1  | [2019-02-28 16:52:13,627: ERROR/ForkPoolWorker-2] Task masu.processor.tasks.update_charge_info[af62173b-b77d-49bf-be34-eca892f14309] raised unexpected: TransactionRollbackError('deadlock detected\nDETAIL:  Process 316 waits for ShareLock on transaction 11639; blocked by process 318.\nProcess 318 waits for ShareLock on transaction 11638; blocked by process 316.\nHINT:  See server log for query details.\nCONTEXT:  while updating tuple (0,22) in relation "reporting_ocpusagelineitem_daily_summary"\n',)
worker_1  | Traceback (most recent call last):
worker_1  |   File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
worker_1  |     R = retval = fun(*args, **kwargs)
worker_1  |   File "/masu/masu/celery/__init__.py", line 75, in __call__
worker_1  |     return self.run(*args, **kwargs)
worker_1  |   File "/masu/masu/processor/tasks.py", line 256, in update_charge_info
worker_1  |     updater.update_charge_info()
worker_1  |   File "/masu/masu/processor/report_charge_updater.py", line 88, in update_charge_info
worker_1  |     self._updater.update_summary_charge_info()
worker_1  |   File "/masu/masu/processor/ocp/ocp_report_charge_updater.py", line 222, in update_summary_charge_info
worker_1  |     self._update_cpu_charge()
worker_1  |   File "/masu/masu/processor/ocp/ocp_report_charge_updater.py", line 157, in _update_cpu_charge
worker_1  |     report_accessor.populate_cpu_charge(total_cpu_charge)
worker_1  |   File "/masu/masu/database/ocp_report_db_accessor.py", line 315, in populate_cpu_charge
worker_1  |     self._cursor.execute(charge_line_sql)
worker_1  | psycopg2.extensions.TransactionRollbackError: deadlock detected
worker_1  | DETAIL:  Process 316 waits for ShareLock on transaction 11639; blocked by process 318.
worker_1  | Process 318 waits for ShareLock on transaction 11638; blocked by process 316.
worker_1  | HINT:  See server log for query details.
worker_1  | CONTEXT:  while updating tuple (0,22) in relation "reporting_ocpusagelineitem_daily_summary"
worker_1  |
worker_1  | [2019-02-28 16:52:13,633: INFO/ForkPoolWorker-2] masu.processor.tasks.update_charge_info[85db80c8-42f3-42ac-b345-f3545f039e45]: update_charge_info called with args:
worker_1  |  schema_name: acct10001,
worker_1  |  provider_uuid: 9ba3e0db-613f-48ad-b66f-ba780b1f3906
worker_1  | [2019-02-28 16:52:13,639: INFO/MainProcess] Received task: masu.processor.tasks.update_charge_info[bf822ac5-51a7-42cd-af29-aa449190c066]
worker_1  | [2019-02-28 16:52:14,329: WARNING/ForkPoolWorker-2] [2019-02-28 16:52:14,329] INFO in ocp_report_charge_updater: Starting charge calculation updates.
worker_1  | [2019-02-28 16:52:14,329: INFO/ForkPoolWorker-2] Starting charge calculation updates.
```

DB logs
```
db_1      | ERROR:  deadlock detected
db_1      | DETAIL:  Process 316 waits for ShareLock on transaction 11639; blocked by process 318.
db_1      |     Process 318 waits for ShareLock on transaction 11638; blocked by process 316.
db_1      |     Process 316: -- Calculate and update the OCP CPU usage charge
db_1      |     UPDATE reporting_ocpusagelineitem_daily_summary SET pod_charge_cpu_core_hours = '1.5822145000000000' WHERE id = '217230';
db_1      |
db_1      |     Process 318: -- Calculate and update the OCP Memory usage charge
db_1      |     UPDATE reporting_ocpusagelineitem_daily_summary SET pod_charge_memory_gigabyte_hours = '131.4417765000000000' WHERE id = '238982';
db_1      |
db_1      | HINT:  See server log for query details.
db_1      | CONTEXT:  while updating tuple (0,22) in relation "reporting_ocpusagelineitem_daily_summary"
db_1      | STATEMENT:  -- Calculate and update the OCP CPU usage charge
db_1      |     UPDATE reporting_ocpusagelineitem_daily_summary SET pod_charge_cpu_core_hours = '1.5822145000000000' WHERE id = '217230';
db_1      |
db_1      | ERROR:  deadlock detected
db_1      | DETAIL:  Process 325 waits for ShareLock on transaction 11647; blocked by process 327.
db_1      |     Process 327 waits for ShareLock on transaction 11646; blocked by process 325.
db_1      |     Process 325: -- Calculate and update the OCP CPU usage charge
db_1      |     UPDATE reporting_ocpusagelineitem_daily_summary SET pod_charge_cpu_core_hours = '1.5477110000000000' WHERE id = '217700';
db_1      |
db_1      |     Process 327: -- Calculate and update the OCP Memory usage charge
db_1      |     UPDATE reporting_ocpusagelineitem_daily_summary SET pod_charge_memory_gigabyte_hours = '224.8562915000000000' WHERE id = '239006';
db_1      |
db_1      | HINT:  See server log for query details.
db_1      | CONTEXT:  while updating tuple (0,22) in relation "reporting_ocpusagelineitem_daily_summary"
db_1      | STATEMENT:  -- Calculate and update the OCP CPU usage charge
db_1      |     UPDATE reporting_ocpusagelineitem_daily_summary SET pod_charge_cpu_core_hours = '1.5477110000000000' WHERE id = '217700';
db_1      |
```

**Comment by lcouzens** [comment]
Verified
Commit: 4bc63891ac27ffa0365680bd83230bdc987d1cae
Added 25 providers with rates using the yml above and didnt hit the deadlock issue.
