### ISSUE TITLE
Investigate AWS processing and bill finalization

### ISSUE THREAD

**Issue by dccurtis** [project-koku/masu#381]
Both `cost-usage-bucket` and `landon-hccm-west` are experiencing the following failure while processing last month's (finalized) data

```
psycopg2.ProgrammingError: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
```

This is reproducible on a local interpreter to rule out any race conditions between the current and last month processing on initial ingest
```
>>> from masu.processor.aws.aws_report_processor import AWSReportProcessor
>>> csv_file = '/Users/curtisd/docker_temp/landon-hccm-west/396fe163-ced9-4417-a151-3723949c5236-landon-cost-usage-west-1.csv.gz'
>>> compression = 'GZIP'
>>> proc = AWSReportProcessor('acct10001', csv_file, compression, 1)
>>> proc.process()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/curtisd/projects/repos/masu_fork/masu/processor/aws/aws_report_processor.py", line 159, in process
    is_finalized = self._save_to_db(temp_table, report_db)
  File "/Users/curtisd/projects/repos/masu_fork/masu/processor/aws/aws_report_processor.py", line 255, in _save_to_db
    self.line_item_conflict_columns
  File "/Users/curtisd/projects/repos/masu_fork/masu/database/report_db_accessor_base.py", line 143, in merge_temp_table
    self._cursor.execute(update_sql)
psycopg2.ProgrammingError: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.

>>>
```

The current month is processed successfully but the number of line items does not match the number of rows in the csv.  Accounting for the header into csv it appears that 2 lines were dropped.
```
postgres=# select count(*) from reporting_awscostentrylineitem;
 count
--------
 931595
(1 row)

postgres=#
```
```
➜  landon-hccm-west cat 45368abb-df26-4745-b57c-45adaf03d6dd-landon-cost-usage-west-1.csv | wc -l
  931598
➜  landon-hccm-west
```

Conflicting lines are dropped while processing a non-finalized report.

This issue is to investigate what is happening with the processor while processing finalized reports and make appropriate changes to ensure finalized reports can be successfully processed.

**Comment by lcouzens** [comment]
I wonder if this is the same issue causing some of the end of month data to be missed. Every account seems to have a drop on the last day sometimes even last 2 days.

```
            "accounts": [
                {
                    "account": "25xxxxxxx",
                    "values": [
                        {
                            "date": "2019-01-30",
                            "units": "USD",
                            "account": "",
                            "total": 9.105243054,
                            "account_alias": ""
                        }
                    ]
                },
                {
                    "account": "",
                    "values": [
                        {
                            "date": "2019-01-30",
                            "units": "USD",
                            "account": "58xxxxxxx",
                            "total": 0.836514169,
                            "account_alias": "hccm-alias"
                        }
                    ]
                }
            ]
        },
        {
            "date": "2019-01-31",
            "accounts": [
                {
                    "account": "xxxxxxxx",
                    "values": [
                        {
                            "date": "2019-01-31",
                            "units": "USD",
                            "account": "",
                            "total": 3.035079568,
                            "account_alias": ""
                        }
                    ]
                },
                {
                    "account": "",
                    "values": [
                        {
                            "date": "2019-01-31",
                            "units": "USD",
                            "account": "",
                            "total": 0.4728,
                            "account_alias": "hccm-alias"
```

**Comment by lcouzens** [comment]
Verified
Commit: aaad2da7866449a8f209dea5ead4e794a98263fd

Steps: I pulled in my real bucket and it actually processed both months now, bonus!
