### ISSUE TITLE
masu-listener stops listening when expected file isn't found (Traceback)

### ISSUE THREAD

**Issue by chambridge** [project-koku/masu#464]
**Describe the bug**
Encountered the following Traceback in production which killed our listening to kafka:
```
[2019-06-12 22:00:34,412] INFO in kafka_msg_handler: Summarization celery uuid: 74a67b7b-3857-4f59-aadc-8b70364f7d43
Task exception was never retrieved
future: <Task finished coro=<process_messages() done, defined at /opt/app-root/src/masu/external/kafka_msg_handler.py:290> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/opt/app-root/src/masu/external/kafka_msg_handler.py", line 303, in process_messages
    status, report_meta = handle_message(msg)
  File "/opt/app-root/src/masu/external/kafka_msg_handler.py", line 224, in handle_message
    report_meta = extract_payload(value['url'])
  File "/opt/app-root/src/masu/external/kafka_msg_handler.py", line 140, in extract_payload
    shutil.copy(payload_source_path, payload_destination_path)
  File "/opt/app-root/lib64/python3.6/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/app-root/lib64/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpvzc2eo53/f9aa6dae-b0c9-5731-9510-36185b83536d/b0dba9d9-41e0-54bf-a178-68ab1d60baea_openshift_usage_report.0.csv'
```

**Expected behavior**
Worst case we should gracefully handle this error and be able to continue to handle messages from Kafka. Perhaps also capture an error metric for Prometheus reporting.

**Comment by lcouzens** [comment]
Verified
Commit: 61349f806eb1394a34d46c017a4b119dc26057cf
