### ISSUE TITLE
Derived Cost Calculation Failing on missing rate or usage.

### ISSUE THREAD

**Issue by adberglund** [project-koku/masu#471]
**Describe the bug**
We are getting a TypeError when trying to multiply usage by a `None`/`null` rate when calculating charge/derived cost.

**Expected behavior**
We should check for a rate and default to 0 if it does not exist. 

**Traceback**

```

[2019-06-28 12:02:32,069: ERROR/ForkPoolWorker-1] Task masu.processor.tasks.update_charge_info[a7472a9d-32c8-448c-b728-261287faa2a3] raised unexpected: TypeError("unsupported operand type(s) for *: 'NoneType' and 'decimal.Decimal'",)
--
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
  | R = retval = fun(*args, **kwargs)
  | File "/opt/app-root/src/masu/celery/__init__.py", line 91, in __call__
  | return self.run(*args, **kwargs)
  | File "/opt/app-root/src/masu/processor/tasks.py", line 279, in update_charge_info
  | updater.update_charge_info(start_date, end_date)
  | File "/opt/app-root/src/masu/processor/report_charge_updater.py", line 95, in update_charge_info
  | self._updater.update_summary_charge_info(start_date, end_date)
  | File "/opt/app-root/src/masu/processor/ocp/ocp_report_charge_updater.py", line 263, in update_summary_charge_info
  | self._update_pod_charge()
  | File "/opt/app-root/src/masu/processor/ocp/ocp_report_charge_updater.py", line 187, in _update_pod_charge
  | cpu_request_charge = self._calculate_charge(cpu_request_rates, cpu_request)
  | File "/opt/app-root/src/masu/processor/ocp/ocp_report_charge_updater.py", line 127, in _calculate_charge
  | charge_value = self._calculate_variable_charge(value, rates)
  | File "/opt/app-root/src/masu/processor/ocp/ocp_report_charge_updater.py", line 118, in _calculate_variable_charge
  | charge += usage_applied * rate
  | TypeError: unsupported operand type(s) for *: 'NoneType' and 'decimal.Decimal'
  | Task masu.processor.tasks.update_charge_info[a7472a9d-32c8-448c-b728-261287faa2a3] raised unexpected: TypeError("unsupported operand type(s) for *: 'NoneType' and 'decimal.Decimal'",)
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
  | R = retval = fun(*args, **kwargs)
  | File "/opt/app-root/src/masu/celery/__init__.py", line 91, in __call__
  | return self.run(*args, **kwargs)
  | File "/opt/app-root/src/masu/processor/tasks.py", line 279, in update_charge_info
  | updater.update_charge_info(start_date, end_date)
  | File "/opt/app-root/src/masu/processor/report_charge_updater.py", line 95, in update_charge_info
  | self._updater.update_summary_charge_info(start_date, end_date)
  | File "/opt/app-root/src/masu/processor/ocp/ocp_report_charge_updater.py", line 263, in update_summary_charge_info
  | self._update_pod_charge()
  | File "/opt/app-root/src/masu/processor/ocp/ocp_report_charge_updater.py", line 187, in _update_pod_charge
  | cpu_request_charge = self._calculate_charge(cpu_request_rates, cpu_request)
  | File "/opt/app-root/src/masu/processor/ocp/ocp_report_charge_updater.py", line 127, in _calculate_charge
  | charge_value = self._calculate_variable_charge(value, rates)
  | File "/opt/app-root/src/masu/processor/ocp/ocp_report_charge_updater.py", line 118, in _calculate_variable_charge
  | charge += usage_applied * rate
  | TypeError: unsupported operand type(s) for *: 'NoneType' and 'decimal.Decimal'


```

**Comment by adberglund** [comment]
@adberglund to add more information on environment and when this happened. Look at Cloud Watch / Kibana

**Comment by blentz** [comment]
I saw this in CI:

```
[2019-07-16 18:08:40,431: WARNING/ForkPoolWorker-1] [2019-07-16 18:08:40,431] INFO in ocp_cloud_summary_updater: Updating OpenShift on OCP cost summary table for
	Schema: acct1460290 
	Provider: a558f057-06b1-460a-b597-58b5ce354fe1 
	Dates: 2019-07-01 - 2019-07-16
[2019-07-16 18:08:40,431] INFO in ocp_cloud_summary_updater: Updating OpenShift on OCP cost summary table for
	Schema: acct1460290 
	Provider: a558f057-06b1-460a-b597-58b5ce354fe1 
	Dates: 2019-07-01 - 2019-07-16
[2019-07-16 18:08:40,431: INFO/ForkPoolWorker-1] Updating OpenShift on OCP cost summary table for
	Schema: acct1460290 
	Provider: a558f057-06b1-460a-b597-58b5ce354fe1 
	Dates: 2019-07-01 - 2019-07-16
Updating OpenShift on OCP cost summary table for
	Schema: acct1460290 
	Provider: a558f057-06b1-460a-b597-58b5ce354fe1 
	Dates: 2019-07-01 - 2019-07-16
[2019-07-16 18:08:40,432: WARNING/ForkPoolWorker-1] [2019-07-16 18:08:40,432] INFO in report_db_accessor_base: Updating reporting_ocpcosts_summary from 2019-07-01 to 2019-07-16.
[2019-07-16 18:08:40,432] INFO in report_db_accessor_base: Updating reporting_ocpcosts_summary from 2019-07-01 to 2019-07-16.
[2019-07-16 18:08:40,432: INFO/ForkPoolWorker-1] Updating reporting_ocpcosts_summary from 2019-07-01 to 2019-07-16.
Updating reporting_ocpcosts_summary from 2019-07-01 to 2019-07-16.
[2019-07-16 18:08:42,236: WARNING/ForkPoolWorker-1] [2019-07-16 18:08:42,236] INFO in report_db_accessor_base: Finished updating reporting_ocpcosts_summary.
[2019-07-16 18:08:42,236] INFO in report_db_accessor_base: Finished updating reporting_ocpcosts_summary.
[2019-07-16 18:08:42,236: INFO/ForkPoolWorker-1] Finished updating reporting_ocpcosts_summary.
Finished updating reporting_ocpcosts_summary.
[2019-07-16 18:08:42,258: INFO/MainProcess] Received task: masu.processor.tasks.update_charge_info[eea475a4-ae9b-4e56-879e-bb246d7fbeea]  
Received task: masu.processor.tasks.update_charge_info[eea475a4-ae9b-4e56-879e-bb246d7fbeea]  
[2019-07-16 18:08:42,258: INFO/ForkPoolWorker-1] Task masu.processor.tasks.update_summary_tables[19e7f3ff-0c71-4d5d-95e5-aafbff622144] succeeded in 422.0987788469065s: None
Task masu.processor.tasks.update_summary_tables[19e7f3ff-0c71-4d5d-95e5-aafbff622144] succeeded in 422.0987788469065s: None
[2019-07-16 18:08:42,260: INFO/ForkPoolWorker-1] masu.processor.tasks.update_charge_info[eea475a4-ae9b-4e56-879e-bb246d7fbeea]: update_charge_info called with args:
 schema_name: acct1460290,
 provider_uuid: a558f057-06b1-460a-b597-58b5ce354fe1
[2019-07-16 18:08:49,603: WARNING/ForkPoolWorker-1] [2019-07-16 18:08:49,603] INFO in ocp_report_charge_updater: Starting charge calculation updates for provider: a558f057-06b1-460a-b597-58b5ce354fe1. Cluster ID: 7d3a2bf6-af3e-53c7-90f1-51f4a9b00ac8.
[2019-07-16 18:08:49,603] INFO in ocp_report_charge_updater: Starting charge calculation updates for provider: a558f057-06b1-460a-b597-58b5ce354fe1. Cluster ID: 7d3a2bf6-af3e-53c7-90f1-51f4a9b00ac8.
[2019-07-16 18:08:49,603: INFO/ForkPoolWorker-1] Starting charge calculation updates for provider: a558f057-06b1-460a-b597-58b5ce354fe1. Cluster ID: 7d3a2bf6-af3e-53c7-90f1-51f4a9b00ac8.
Starting charge calculation updates for provider: a558f057-06b1-460a-b597-58b5ce354fe1. Cluster ID: 7d3a2bf6-af3e-53c7-90f1-51f4a9b00ac8.
[2019-07-16 18:08:51,233: WARNING/ForkPoolWorker-1] [2019-07-16 18:08:51,233] INFO in ocp_rate_db_accessor: OCP CPU usage rates: {'tiered_rate': [{'unit': 'USD', 'value': '0.0070000000', 'usage_end': None, 'usage_start': None}]}
[2019-07-16 18:08:51,233] INFO in ocp_rate_db_accessor: OCP CPU usage rates: {'tiered_rate': [{'unit': 'USD', 'value': '0.0070000000', 'usage_end': None, 'usage_start': None}]}
[2019-07-16 18:08:51,233: INFO/ForkPoolWorker-1] OCP CPU usage rates: {'tiered_rate': [{'unit': 'USD', 'value': '0.0070000000', 'usage_end': None, 'usage_start': None}]}
OCP CPU usage rates: {'tiered_rate': [{'unit': 'USD', 'value': '0.0070000000', 'usage_end': None, 'usage_start': None}]}
[2019-07-16 18:08:51,236: WARNING/ForkPoolWorker-1] [2019-07-16 18:08:51,236] INFO in ocp_rate_db_accessor: OCP CPU request rates: {'tiered_rate': [{'unit': 'USD', 'value': '0.2000000000', 'usage_end': None, 'usage_start': None}]}
[2019-07-16 18:08:51,236] INFO in ocp_rate_db_accessor: OCP CPU request rates: {'tiered_rate': [{'unit': 'USD', 'value': '0.2000000000', 'usage_end': None, 'usage_start': None}]}
[2019-07-16 18:08:51,236: INFO/ForkPoolWorker-1] OCP CPU request rates: {'tiered_rate': [{'unit': 'USD', 'value': '0.2000000000', 'usage_end': None, 'usage_start': None}]}
OCP CPU request rates: {'tiered_rate': [{'unit': 'USD', 'value': '0.2000000000', 'usage_end': None, 'usage_start': None}]}
[2019-07-16 18:08:51,238: WARNING/ForkPoolWorker-1] [2019-07-16 18:08:51,238] INFO in ocp_rate_db_accessor: OCP Memory usage rates: {'tiered_rate': [{'unit': 'USD', 'value': '0.0090000000', 'usage_end': None, 'usage_start': None}]}
[2019-07-16 18:08:51,238] INFO in ocp_rate_db_accessor: OCP Memory usage rates: {'tiered_rate': [{'unit': 'USD', 'value': '0.0090000000', 'usage_end': None, 'usage_start': None}]}
[2019-07-16 18:08:51,238: INFO/ForkPoolWorker-1] OCP Memory usage rates: {'tiered_rate': [{'unit': 'USD', 'value': '0.0090000000', 'usage_end': None, 'usage_start': None}]}
OCP Memory usage rates: {'tiered_rate': [{'unit': 'USD', 'value': '0.0090000000', 'usage_end': None, 'usage_start': None}]}
[2019-07-16 18:08:51,244: WARNING/ForkPoolWorker-1] [2019-07-16 18:08:51,244] INFO in ocp_rate_db_accessor: OCP Memory request rates: {'tiered_rate': [{'unit': 'USD', 'value': '0.0500000000', 'usage_end': None, 'usage_start': None}]}
[2019-07-16 18:08:51,244] INFO in ocp_rate_db_accessor: OCP Memory request rates: {'tiered_rate': [{'unit': 'USD', 'value': '0.0500000000', 'usage_end': None, 'usage_start': None}]}
[2019-07-16 18:08:51,244: INFO/ForkPoolWorker-1] OCP Memory request rates: {'tiered_rate': [{'unit': 'USD', 'value': '0.0500000000', 'usage_end': None, 'usage_start': None}]}
OCP Memory request rates: {'tiered_rate': [{'unit': 'USD', 'value': '0.0500000000', 'usage_end': None, 'usage_start': None}]}
[2019-07-16 18:08:54,219: ERROR/ForkPoolWorker-1] Task masu.processor.tasks.update_charge_info[eea475a4-ae9b-4e56-879e-bb246d7fbeea] raised unexpected: TypeError("unsupported operand type(s) for *: 'NoneType' and 'decimal.Decimal'",)
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/app-root/src/masu/celery/__init__.py", line 91, in __call__
    return self.run(*args, **kwargs)
  File "/opt/app-root/src/masu/processor/tasks.py", line 279, in update_charge_info
    updater.update_charge_info(start_date, end_date)
  File "/opt/app-root/src/masu/processor/report_charge_updater.py", line 95, in update_charge_info
    self._updater.update_summary_charge_info(start_date, end_date)
  File "/opt/app-root/src/masu/processor/ocp/ocp_report_charge_updater.py", line 263, in update_summary_charge_info
    self._update_pod_charge()
  File "/opt/app-root/src/masu/processor/ocp/ocp_report_charge_updater.py", line 187, in _update_pod_charge
    cpu_request_charge = self._calculate_charge(cpu_request_rates, cpu_request)
  File "/opt/app-root/src/masu/processor/ocp/ocp_report_charge_updater.py", line 127, in _calculate_charge
    charge_value = self._calculate_variable_charge(value, rates)
  File "/opt/app-root/src/masu/processor/ocp/ocp_report_charge_updater.py", line 118, in _calculate_variable_charge
    charge += usage_applied * rate
TypeError: unsupported operand type(s) for *: 'NoneType' and 'decimal.Decimal'
Task masu.processor.tasks.update_charge_info[eea475a4-ae9b-4e56-879e-bb246d7fbeea] raised unexpected: TypeError("unsupported operand type(s) for *: 'NoneType' and 'decimal.Decimal'",)
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/app-root/src/masu/celery/__init__.py", line 91, in __call__
    return self.run(*args, **kwargs)
  File "/opt/app-root/src/masu/processor/tasks.py", line 279, in update_charge_info
    updater.update_charge_info(start_date, end_date)
  File "/opt/app-root/src/masu/processor/report_charge_updater.py", line 95, in update_charge_info
    self._updater.update_summary_charge_info(start_date, end_date)
  File "/opt/app-root/src/masu/processor/ocp/ocp_report_charge_updater.py", line 263, in update_summary_charge_info
    self._update_pod_charge()
  File "/opt/app-root/src/masu/processor/ocp/ocp_report_charge_updater.py", line 187, in _update_pod_charge
    cpu_request_charge = self._calculate_charge(cpu_request_rates, cpu_request)
  File "/opt/app-root/src/masu/processor/ocp/ocp_report_charge_updater.py", line 127, in _calculate_charge
    charge_value = self._calculate_variable_charge(value, rates)
  File "/opt/app-root/src/masu/processor/ocp/ocp_report_charge_updater.py", line 118, in _calculate_variable_charge
    charge += usage_applied * rate
TypeError: unsupported operand type(s) for *: 'NoneType' and 'decimal.Decimal'
```

**Comment by dccurtis** [comment]
Saw this again on CI.  Here's some database debug:

`pod_request_cpu_core_hours` and `pod_request_memory_gigabyte_hours` have NULL entries

```
koku=> select usage_start, pod_request_cpu_core_hours from reporting_ocpusagelineitem_daily_summary where cluster_id='7d3a2bf6-af3e-53c7-90f1-51f4a9b00ac8' and pod_request_cpu_core_hours is null group by usage_start, pod_request_cpu_core_hours;
      usage_start       | pod_request_cpu_core_hours
------------------------+----------------------------
 2019-07-08 00:00:00+00 |
 2019-07-07 00:00:00+00 |
 2019-07-15 00:00:00+00 |
 2019-07-05 00:00:00+00 |
 2019-07-09 00:00:00+00 |
 2019-07-02 00:00:00+00 |
 2019-07-03 00:00:00+00 |
 2019-07-12 00:00:00+00 |
 2019-07-06 00:00:00+00 |
 2019-07-13 00:00:00+00 |
 2019-07-16 00:00:00+00 |
 2019-07-10 00:00:00+00 |
 2019-07-11 00:00:00+00 |
 2019-07-14 00:00:00+00 |
 2019-07-01 00:00:00+00 |
 2019-07-04 00:00:00+00 |
(16 rows)

koku=>
```

```
koku=> select usage_start, pod_usage_cpu_core_hours from reporting_ocpusagelineitem_daily_summary where cluster_id='7d3a2bf6-af3e-53c7-90f1-51f4a9b00ac8' and pod_usage_cpu_core_hours is null group by usage_start, pod_usage_cpu_core_hours;
 usage_start | pod_usage_cpu_core_hours
-------------+--------------------------
(0 rows)

koku=>
```

```
koku=> select usage_start, pod_usage_memory_gigabyte_hours from reporting_ocpusagelineitem_daily_summary where cluster_id='7d3a2bf6-af3e-53c7-90f1-51f4a9b00ac8' and pod_usage_memory_gigabyte_hours is null group by usage_start, pod_usage_memory_gigabyte_hours;
 usage_start | pod_usage_memory_gigabyte_hours
-------------+---------------------------------
(0 rows)

koku=>
```

```
koku=> select usage_start, pod_request_memory_gigabyte_hours from reporting_ocpusagelineitem_daily_summary where cluster_id='7d3a2bf6-af3e-53c7-90f1-51f4a9b00ac8' and pod_request_memory_gigabyte_hours is null group by usage_start, pod_request_memory_gigabyte_hours;
      usage_start       | pod_request_memory_gigabyte_hours
------------------------+-----------------------------------
 2019-07-08 00:00:00+00 |
 2019-07-07 00:00:00+00 |
 2019-07-06 00:00:00+00 |
 2019-07-15 00:00:00+00 |
 2019-07-05 00:00:00+00 |
 2019-07-09 00:00:00+00 |
 2019-07-13 00:00:00+00 |
 2019-07-16 00:00:00+00 |
 2019-07-10 00:00:00+00 |
 2019-07-11 00:00:00+00 |
 2019-07-02 00:00:00+00 |
 2019-07-14 00:00:00+00 |
 2019-07-01 00:00:00+00 |
 2019-07-03 00:00:00+00 |
 2019-07-04 00:00:00+00 |
 2019-07-12 00:00:00+00 |
(16 rows)

koku=>
```

**Comment by dccurtis** [comment]
```
koku=> select pod_request_cpu_core_seconds, pod_request_memory_byte_seconds from reporting_ocpusagelineitem_daily where cluster_id='7d3a2bf6-af3e-53c7-90f1-51f4a9b00ac8' limit 15;
 pod_request_cpu_core_seconds | pod_request_memory_byte_seconds
------------------------------+---------------------------------
                  8640.000000 |           23192823398400.000000
                              |
                  8640.000000 |           23192823398400.000000
                              |
                              |
                              |
                              |
                              |
                              |           46385646796800.000000
                              |           46385646796800.000000
                              |           46385646796800.000000
                 21600.000000 |           67947724800000.000000
                 21600.000000 |           31708938240000.000000
                 43200.000000 |           58888028160000.000000
                  8640.000000 |           45298483200000.000000
(15 rows)

koku=>
```
Missing from daily table as well

**Comment by dccurtis** [comment]
Missing from line item for this cluster

```
koku=> select * from reporting_ocpusagereportperiod where cluster_id='7d3a2bf6-af3e-53c7-90f1-51f4a9b00ac8';
  id  |              cluster_id              |  report_period_start   |   report_period_end    | provider_id | summary_data_creation_datetime | summary_data_updated_datetime |     derived_cost_datetime
------+--------------------------------------+------------------------+------------------------+-------------+--------------------------------+-------------------------------+-------------------------------
 3112 | 7d3a2bf6-af3e-53c7-90f1-51f4a9b00ac8 | 2019-06-01 00:00:00+00 | 2019-07-01 00:00:00+00 |        3631 | 2019-06-07 01:02:01.127002+00  | 2019-06-30 23:51:03.717612+00 | 2019-06-21 18:46:08.360258+00
 1965 | 7d3a2bf6-af3e-53c7-90f1-51f4a9b00ac8 | 2019-05-01 00:00:00+00 | 2019-06-01 00:00:00+00 |        3631 | 2019-05-01 11:38:37.756235+00  | 2019-05-07 02:15:38.56308+00  |
 4087 | 7d3a2bf6-af3e-53c7-90f1-51f4a9b00ac8 | 2019-07-01 00:00:00+00 | 2019-08-01 00:00:00+00 |        3631 | 2019-07-03 00:01:48.627807+00  | 2019-07-16 19:58:47.756236+00 |
(3 rows)

koku=>

koku=> select report_period_id, pod_request_cpu_core_seconds, pod_request_memory_byte_seconds from reporting_ocpusagelineitem where pod_request_cpu_core_seconds is null or pod_request_memory_byte_seconds is null and report_period_id in (3112, 1965, 4087) limit 25;
 report_period_id | pod_request_cpu_core_seconds | pod_request_memory_byte_seconds
------------------+------------------------------+---------------------------------
             3112 |                              |             754974720000.000000
             3112 |                              |             754974720000.000000
             3112 |                              |             754974720000.000000
             3112 |                              |             754974720000.000000
             3112 |                              |             754974720000.000000
             3112 |                              |             754974720000.000000
             3112 |                              |             754974720000.000000
             3112 |                              |             754974720000.000000
             3112 |                              |             754974720000.000000
             3698 |                              |             754974720000.000000
             3112 |                              |             754974720000.000000
             3112 |                              |             754974720000.000000
             3112 |                              |             754974720000.000000
             3698 |                              |             754974720000.000000
             3112 |                              |             754974720000.000000
             3698 |                              |             754974720000.000000
             3698 |                              |             754974720000.000000
             3698 |                              |             754974720000.000000
             3698 |                              |             754974720000.000000
             3698 |                              |
             3698 |                              |
             3112 |                              |             754974720000.000000
             3112 |                              |             754974720000.000000
             3112 |                              |             754974720000.000000
             3698 |                              |             754974720000.000000
(25 rows)
```

**Comment by dccurtis** [comment]
Full list of pod names where pod_request_cpu_core_seconds or pod_request_memory_byte_seconds is NULL

[missing_metrics_pod_names.txt](https://github.com/project-koku/masu/files/3399090/missing_metrics_pod_names.txt)

**Comment by dccurtis** [comment]
based on these pod names I suspect this could be some fallout from https://github.com/project-koku/korekuta/pull/80

**Comment by dchorvat1** [comment]
Verified, commit a3e62de936b0ec3aeae6382d9237a85a9b5dfb1a
