### ISSUE TITLE
Insights Local directory needs to be cleared periodically

### ISSUE THREAD

**Issue by dccurtis** [project-koku/masu#476]
**Describe the bug**
The `insights_local` directory is used as a temporary staging area to extract OCP payloads.  The OCP downloader picks up files in this directory.

We are currently not removing files from the directory once processing completes successfully.  

Failure to remove processed files can lead to out of space problems in the Masu-listener.

Example:
```
[2019-07-14 16:01:46,705] INFO in kafka_msg_handler: Processing: {'files': ['5066698a-e6cf-576d-b579-6e8d4c8144e9_openshift_usage_report.0.csv', '5066698a-e6cf-576d-b579-6e8d4c8144e9_openshift_usage_report.1.csv'], 'date': datetime.datetime(2019, 7, 14, 16, 0, 6, tzinfo=tzlocal()), 'uuid': '5066698a-e6cf-576d-b579-6e8d4c8144e9', 'cluster_id': '29188b91-c6f3-5411-ade4-5b0248f652ca', 'manifest_path': '/var/tmp/masu/tmppeavqfwv/29188b91-c6f3-5411-ade4-5b0248f652ca/manifest.json'} complete.
Task exception was never retrieved
future: <Task finished coro=<process_messages() done, defined at /opt/app-root/src/masu/external/kafka_msg_handler.py:301> exception=OSError(28, 'No space left on device')>
Traceback (most recent call last):
 File "/opt/app-root/src/masu/external/kafka_msg_handler.py", line 314, in process_messages
   status, report_meta = handle_message(msg)
 File "/opt/app-root/src/masu/external/kafka_msg_handler.py", line 231, in handle_message
   report_meta = extract_payload(value['url'])
 File "/opt/app-root/src/masu/external/kafka_msg_handler.py", line 144, in extract_payload
   shutil.copy(payload_source_path, payload_destination_path)
 File "/opt/app-root/lib64/python3.6/shutil.py", line 241, in copy
   copyfile(src, dst, follow_symlinks=follow_symlinks)
 File "/opt/app-root/lib64/python3.6/shutil.py", line 122, in copyfile
   copyfileobj(fsrc, fdst)
 File "/opt/app-root/lib64/python3.6/shutil.py", line 82, in copyfileobj
   fdst.write(buf)
OSError: [Errno 28] No space left on device 
```
**Expected behavior**
Temporary files should be removed when they are no longer needed.

**Comment by lcouzens** [comment]
Verified
Commit: c158d0b71402ba2215e398231a31ce8bfbe973d9
